name: Test definitions

on:
  workflow_call:

jobs:
  Validate:
    name: Test definitions
    steps:
      - uses: actions/checkout@v2

      - name: Install openapi-to-fastapi
        run: pip install openapi-to-fastapi

      - name: Run tests
        run: openapi-validator --path ./DataProducts -v IhanStandardsValidator
